DROP DATABASE IF EXISTS cars_db`;
CREATE DATABASE `cars_db`;
USE `cars_db`;

CREATE TABLE profile(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR (50) NOT NULL
    userid VARCHAR (300),
    email VARCHAR (50)
);

// ORIGINALLY WAS THIS
DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;